FROM apache/airflow:2.9.0

USER root
RUN apt-get update && apt-get install -y default-jdk && apt-get clean

USER airflow
COPY requirements_airflow.txt /tmp/requirements_airflow.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /tmp/requirements_airflow.txt \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.0/constraints-3.12.txt"
